version: "2"
run:
  issues-exit-code: 1
linters:
  enable:
    - asciicheck
    - dogsled
    - exhaustive
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gosec
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - unconvert
    - unparam
    - whitespace
    - wsl_v5
  disable:
    - dupl
    - funlen
    - ineffassign
    - prealloc
    - testpackage
  settings:
    whitespace:
      multi-if: false
      multi-func: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      strict-append: true
      allow-assign-and-call: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-cuddle-declarations: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - goconst
        path: _test\.go
    paths:
      - api
      - controllers/runner
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - gitlab.com/gitlab-org/cloud-native/gitlab-operator
  exclusions:
    generated: lax
    paths:
      - api
      - controllers/runner
      - third_party$
      - builtin$
      - examples$
