[tools]
github-cli =  "2.86.0"
golang =  "1.25.7"
golangci-lint =  "2.4.0"
helm =  "4.1.0"
kind =  "0.27.0"
kubebuilder =  "4.11.1"
operator-sdk =  "1.39.2"
'github:operator-framework/operator-registry' =  "1.51.0"
task =  "3.42.1"
tekton-cli =  "0.32.0"
yq =  "4.52.2"

# For linting documentation
markdownlint-cli2 = "0.19.0"
lychee = "0.21.0"
vale = "3.13.0"
