/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chart-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the GitLab chart versions the Operator bundles */
        get: operations["list-chart-versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitLab resources across all watched namespaces */
        get: operations["list-gitlabs-all-namespaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces/{namespace}/gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitLab resources in a namespace */
        get: operations["list-gitlabs"];
        put?: never;
        /** Create a GitLab resource */
        post: operations["create-gitlab"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces/{namespace}/gitlabs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a GitLab resource */
        get: operations["get-gitlab"];
        /** Update a GitLab resource */
        put: operations["update-gitlab"];
        post?: never;
        /** Delete a GitLab resource */
        delete: operations["delete-gitlab"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChartDTO: {
            /** @description Free-form Helm values used to render the GitLab Chart. They are merged over the values derived from the structured fields and win on conflict. */
            values?: {
                [key: string]: unknown;
            };
            /** @description Semantic version of the GitLab Chart. */
            version?: string;
        };
        ChartVersionsDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChartVersionsDTO.json
             */
            readonly $schema?: string;
            /** @description GitLab chart versions the Operator carries, newest first. */
            versions: string[] | null;
        };
        Condition: {
            lastTransitionTime: string;
            message: string;
            /** Format: int64 */
            observedGeneration?: number;
            reason: string;
            status: string;
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GitLabList: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitLabList.json
             */
            readonly $schema?: string;
            /** @description The GitLab resources. */
            items: components["schemas"]["GitLabResource"][] | null;
        };
        GitLabResource: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitLabResource.json
             */
            readonly $schema?: string;
            /** @description GitLab Chart configuration. */
            chart: components["schemas"]["ChartDTO"];
            /**
             * @description GitLab edition to deploy: 'ee' for Enterprise Edition, which runs unlicensed with the Free feature set, or 'ce' for Community Edition.
             * @example ee
             * @enum {string}
             */
            edition?: "ce" | "ee";
            /**
             * @description Fully qualified domain name the GitLab instance is reached at.
             * @example gitlab.example.com
             */
            hostname?: string;
            /** @description Labels applied to the GitLab resource. */
            labels?: {
                [key: string]: string;
            };
            /** @description Reference to the GitLab license to activate the instance with. */
            license?: components["schemas"]["LicenseDTO"];
            /** @description Name of the GitLab resource. */
            name: string;
            /** @description Namespace the GitLab resource lives in. */
            namespace: string;
            /** @description S3 compatible object storage the instance keeps its artifacts, uploads, and other blobs in. The chart needs one: it enables object storage for these with no connection of its own. See https://docs.gitlab.com/charts/charts/globals/#connection. */
            objectStorage?: components["schemas"]["ObjectStorageDTO"];
            /** @description PostgreSQL server the instance stores its data in. The chart bundles no database. See https://docs.gitlab.com/install/requirements/#postgresql. */
            postgresql?: components["schemas"]["PostgreSQLDTO"];
            /** @description Redis server the instance uses for caching, queues, and shared state; Valkey serves as a drop-in replacement. The chart bundles no server. See https://docs.gitlab.com/install/requirements/#redis. */
            redis?: components["schemas"]["RedisDTO"];
            /** @description Most recently observed status. Read-only. */
            readonly status?: components["schemas"]["StatusDTO"];
        };
        LicenseDTO: {
            /** @description Key of the Secret that holds the license. */
            secretRef: components["schemas"]["SecretRefDTO"];
        };
        ObjectStorageDTO: {
            /** @description Key of the Secret that holds the connection settings. */
            connectionSecretRef: components["schemas"]["SecretRefDTO"];
        };
        PostgreSQLDTO: {
            /**
             * @description Hostname of the PostgreSQL server.
             * @example gitlab-postgresql.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of the database user. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
        };
        RedisDTO: {
            /**
             * @description Hostname of the Redis server.
             * @example gitlab-valkey.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of the server. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
        };
        SecretRefDTO: {
            /** @description Key of the Secret to read. */
            key: string;
            /** @description Name of the Secret. */
            name: string;
        };
        StatusDTO: {
            /** @description Detailed status conditions. */
            conditions?: components["schemas"]["Condition"][] | null;
            /** @description Deployed GitLab version, such as 19.3.2. */
            gitlabVersion?: string;
            /** @description Current lifecycle phase. */
            phase?: string;
            /** @description Deployed GitLab chart version, an unrelated number to the GitLab version it deploys. */
            version?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-chart-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartVersionsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-gitlabs-all-namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitLabResource"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitLabResource"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
