/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chart-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the GitLab chart versions available to install or upgrade to */
        get: operations["list-chart-versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitLab resources across all watched namespaces */
        get: operations["list-gitlabs-all-namespaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces/{namespace}/gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitLab resources in a namespace */
        get: operations["list-gitlabs"];
        put?: never;
        /** Create a GitLab resource */
        post: operations["create-gitlab"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces/{namespace}/gitlabs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a GitLab resource */
        get: operations["get-gitlab"];
        /** Update a GitLab resource */
        put: operations["update-gitlab"];
        post?: never;
        /** Delete a GitLab resource */
        delete: operations["delete-gitlab"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces/{namespace}/gitlabs/{name}/siphon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the Siphon of a GitLab instance */
        get: operations["get-siphon"];
        /** Create or replace the Siphon of a GitLab instance */
        put: operations["put-siphon"];
        post?: never;
        /** Delete the Siphon of a GitLab instance */
        delete: operations["delete-siphon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChartDTO: {
            /** @description Free-form Helm values used to render the chart. They are merged over the values derived from the structured fields and win on conflict. */
            values?: {
                [key: string]: unknown;
            };
            /** @description Semantic version of the Helm chart. */
            version?: string;
        };
        ChartVersionsDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChartVersionsDTO.json
             */
            readonly $schema?: string;
            /** @description GitLab chart versions the Operator carries, newest first. */
            versions: string[] | null;
        };
        Condition: {
            lastTransitionTime: string;
            message: string;
            /** Format: int64 */
            observedGeneration?: number;
            reason: string;
            status: string;
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GitLabList: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitLabList.json
             */
            readonly $schema?: string;
            /** @description The GitLab resources. */
            items: components["schemas"]["GitLabResource"][] | null;
        };
        GitLabResource: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitLabResource.json
             */
            readonly $schema?: string;
            /** @description GitLab Chart configuration. */
            chart: components["schemas"]["ChartDTO"];
            /**
             * @description GitLab edition to deploy: 'ee' for Enterprise Edition, which runs unlicensed with the Free feature set, or 'ce' for Community Edition.
             * @example ee
             * @enum {string}
             */
            edition?: "ce" | "ee";
            /**
             * @description Fully qualified domain name the GitLab instance is reached at.
             * @example gitlab.example.com
             */
            hostname?: string;
            /** @description Labels applied to the GitLab resource. */
            labels?: {
                [key: string]: string;
            };
            /** @description Reference to the GitLab license to activate the instance with. */
            license?: components["schemas"]["LicenseDTO"];
            /** @description Name of the GitLab resource. */
            name: string;
            /** @description Namespace the GitLab resource lives in. */
            namespace: string;
            /** @description S3 compatible object storage the instance keeps its artifacts, uploads, and other blobs in. The chart needs one: it enables object storage for these with no connection of its own. See https://docs.gitlab.com/charts/charts/globals/#connection. */
            objectStorage?: components["schemas"]["ObjectStorageDTO"];
            /** @description Backs the GitLab Secret Manager with an OpenBao instance. Naming it turns on both the GitLab-side integration and the bundled OpenBao subchart. See https://docs.gitlab.com/charts/charts/openbao/#setup-gitlab-secret-manager-and-openbao. */
            openbao?: components["schemas"]["OpenBaoDTO"];
            /** @description PostgreSQL server the instance stores its data in. The chart bundles no database. See https://docs.gitlab.com/install/requirements/#postgresql. */
            postgresql?: components["schemas"]["PostgreSQLDTO"];
            /** @description Redis server the instance uses for caching, queues, and shared state; Valkey serves as a drop-in replacement. The chart bundles no server. See https://docs.gitlab.com/install/requirements/#redis. */
            redis?: components["schemas"]["RedisDTO"];
            /** @description Most recently observed status. Read-only. */
            readonly status?: components["schemas"]["StatusDTO"];
        };
        LicenseDTO: {
            /** @description Key of the Secret that holds the license. */
            secretRef: components["schemas"]["SecretRefDTO"];
        };
        LocalSecretRefDTO: {
            /** @description Name of the Secret. */
            name: string;
        };
        ObjectStorageDTO: {
            /** @description Key of the Secret that holds the connection settings. */
            connectionSecretRef: components["schemas"]["SecretRefDTO"];
        };
        OpenBaoDTO: {
            /** @description PostgreSQL server OpenBao stores its data in, separate from the database of the GitLab instance itself. OpenBao does not inherit that database's password. */
            postgresql: components["schemas"]["OpenBaoPostgreSQLDTO"];
            /** @description Pre-existing ServiceAccount OpenBao's pod runs as. OpenBao needs a Role granting get/update/patch on Pods and a RoleBinding to it, neither of which the bridge or the Operator creates: RBAC is not managed on the cluster they reconcile. Create both ahead of time. */
            serviceAccount: components["schemas"]["OpenBaoServiceAccountDTO"];
        };
        OpenBaoPostgreSQLDTO: {
            /**
             * @description Database OpenBao stores its data in. Defaults to 'openbao'.
             * @example openbao
             */
            database?: string;
            /**
             * @description Hostname of the PostgreSQL server.
             * @example openbao-postgresql.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of the database user. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
            /**
             * Format: int32
             * @description Port of the PostgreSQL server. Defaults to 5432.
             * @example 5432
             */
            port?: number;
            /**
             * @description Login role OpenBao connects as. Defaults to 'openbao'.
             * @example openbao
             */
            username?: string;
        };
        OpenBaoServiceAccountDTO: {
            /** @description Name of the ServiceAccount, already granted the Role OpenBao needs. */
            name: string;
        };
        PostgreSQLDTO: {
            /**
             * @description Hostname of the PostgreSQL server.
             * @example gitlab-postgresql.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of the database user. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
        };
        RedisDTO: {
            /**
             * @description Hostname of the Redis server.
             * @example gitlab-valkey.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of the server. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
        };
        SecretRefDTO: {
            /** @description Key of the Secret to read. */
            key: string;
            /** @description Name of the Secret. */
            name: string;
        };
        SiphonQueueAuthDTO: {
            /** @description Key of the Secret that holds the password. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
            /** @description Key of the Secret that holds the user name. */
            usernameSecretRef: components["schemas"]["SecretRefDTO"];
        };
        SiphonQueueDTO: {
            /** @description User name and password the client authenticates with. Leave it out for a server that accepts anonymous clients. */
            auth?: components["schemas"]["SiphonQueueAuthDTO"];
            /** @description Client certificate the connection presents. */
            tls?: components["schemas"]["SiphonQueueTLSDTO"];
            /**
             * @description URL of the NATS server.
             * @example nats://nats.nats.svc.cluster.local:4222
             */
            url: string;
        };
        SiphonQueueTLSDTO: {
            /**
             * @description Key holding the certificate authority bundle. Defaults to 'ca.crt'.
             * @example ca.crt
             */
            caCertKey?: string;
            /**
             * @description Key holding the client certificate. Defaults to 'tls.crt'.
             * @example tls.crt
             */
            clientCertKey?: string;
            /**
             * @description Key holding the client private key. Defaults to 'tls.key'.
             * @example tls.key
             */
            clientKeyKey?: string;
            /** @description Name of the Secret in the namespace of the resource. */
            secretName: string;
        };
        SiphonResource: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SiphonResource.json
             */
            readonly $schema?: string;
            /** @description Siphon chart configuration. Only a version the Operator bundles renders: unlike the GitLab chart, a Siphon chart is never pulled. */
            chart: components["schemas"]["ChartDTO"];
            /** @description Name of the GitLabCore instance whose database this pipeline streams. */
            readonly gitlabRef?: string;
            /** @description Name of the Siphon resource. The bridge derives it from the GitLab instance when it creates one. */
            readonly name?: string;
            /** @description Namespace the Siphon resource lives in, which is the namespace of the GitLab instance. */
            readonly namespace?: string;
            /** @description NATS server the stream passes through. JetStream must be enabled: Siphon uses streams, a key-value bucket, and an object store. */
            queue: components["schemas"]["SiphonQueueDTO"];
            /** @description ClickHouse server the stream is written to, over the native protocol. Its target tables are created by the ClickHouse migrations of GitLab, not by Siphon. */
            sink: components["schemas"]["SiphonSinkDTO"];
            /** @description PostgreSQL server the change data capture stream reads. It must be the primary: a logical replication slot is not created on a standby. */
            source: components["schemas"]["SiphonSourceDTO"];
            /** @description Most recently observed status. Read-only. */
            readonly status?: components["schemas"]["SiphonStatusDTO"];
            /** @description How the table definitions of the deployed GitLab version reach the pods. They ship as an OCI image tagged with the GitLab version the referenced instance runs. */
            tables?: components["schemas"]["SiphonTablesDTO"];
        };
        SiphonSinkDTO: {
            /**
             * @description Database holding the target tables.
             * @example gitlab_clickhouse_main_production
             */
            database: string;
            /**
             * @description Hostname of the ClickHouse server.
             * @example clickhouse.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of that user. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
            /**
             * Format: int32
             * @description Port of the ClickHouse native protocol, not of the HTTP interface. Defaults to 9000; 8123 is the HTTP interface, which Siphon does not speak.
             * @example 9000
             */
            port?: number;
            /** @description Turns TLS on for the native protocol connection. The port changes with it, so set both. */
            ssl?: boolean;
            /**
             * @description ClickHouse user the consumer and the reconciler connect as. It needs INSERT and SELECT on the target tables.
             * @example gitlab
             */
            username: string;
        };
        SiphonSourceDTO: {
            /**
             * Format: int32
             * @description PostgreSQL advisory lock the producer takes to elect itself. Defaults to 1; change it only to run a second, independent stream off the same database.
             */
            advisoryLockID?: number;
            /**
             * @description Database to replicate. Defaults to 'gitlabhq_production' and is immutable: changing it re-snapshots every table.
             * @example gitlabhq_production
             */
            database?: string;
            /**
             * @description Hostname of the PostgreSQL primary.
             * @example gitlab-postgresql-rw.databases.svc.cluster.local
             */
            host: string;
            /** @description Key of the Secret that holds the password of that role. */
            passwordSecretRef: components["schemas"]["SecretRefDTO"];
            /**
             * Format: int32
             * @description Port of the PostgreSQL server. Defaults to 5432.
             * @example 5432
             */
            port?: number;
            /**
             * @description libpq TLS mode of the connection. Defaults to 'require'.
             * @example require
             * @enum {string}
             */
            sslMode?: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";
            /**
             * @description Login role the producer connects as. It needs REPLICATION, EXECUTE on siphon_alter_publication, and SELECT on the replicated tables. Defaults to 'siphon'.
             * @example siphon
             */
            user?: string;
        };
        SiphonStatusDTO: {
            /** @description Detailed status conditions. */
            conditions?: components["schemas"]["Condition"][] | null;
            /** @description Application version of the referenced instance, the version the table definitions are pinned to. */
            gitlabVersion?: string;
            /** @description Current lifecycle phase. */
            phase?: string;
            /** @description PostgreSQL publication the producer reads. Deleting the resource leaves it behind. */
            publication?: string;
            /** @description PostgreSQL replication slot the producer holds. Deleting the resource leaves it behind. */
            replicationSlot?: string;
            /** @description NATS JetStream stream the events pass through. Deleting the resource leaves it behind. */
            streamName?: string;
            /**
             * Format: int32
             * @description How many table definitions the pipeline carries.
             */
            tableCount?: number;
            /** @description Fully resolved table definitions image reference. */
            tablesImage?: string;
            /** @description What the table definitions source resolved to, 'ImageVolume' or 'ConfigMap'. */
            tablesSource?: string;
            /** @description Deployed Siphon chart version. */
            version?: string;
        };
        SiphonTablesDTO: {
            /** @description Overrides the table definitions image. Left out, it is the GitLab image tagged with the application version of the referenced instance. */
            image?: string;
            /** @description A kubernetes.io/dockerconfigjson Secret the image is pulled with. Leave it out for the public image. */
            pullSecretRef?: components["schemas"]["LocalSecretRefDTO"];
            /**
             * @description Where the definitions come from. 'ImageVolume' mounts the image into the pod, which needs a runtime that serves OCI image volumes. 'ConfigMap' has the Operator extract it. 'Auto', the default, resolves to 'ConfigMap'.
             * @example Auto
             * @enum {string}
             */
            source?: "Auto" | "ImageVolume" | "ConfigMap";
        };
        StatusDTO: {
            /** @description Detailed status conditions. */
            conditions?: components["schemas"]["Condition"][] | null;
            /** @description Deployed GitLab version, such as 19.3.2. */
            gitlabVersion?: string;
            /** @description Current lifecycle phase. */
            phase?: string;
            /** @description Deployed GitLab chart version, an unrelated number to the GitLab version it deploys. */
            version?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-chart-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartVersionsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-gitlabs-all-namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-gitlabs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitLabResource"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitLabResource"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLabResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-siphon": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiphonResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-siphon": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiphonResource"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiphonResource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-siphon": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespace of the GitLab resource. */
                namespace: string;
                /** @description Name of the GitLab resource. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
