# GKE 1.35
build_review_gke135:
  extends: .build_review_template
  variables:
    DOMAIN: $DOMAIN_GKE135

create_review_gke135:
  extends: .create_review_template
  environment: &environment_gke135
    name: &env_gke_name135 operator135_review/$CI_COMMIT_SHORT_SHA$ENVIRONMENT_SUFFIX-$CI_COMMIT_REF_SLUG
    url: https://gitlab-$TESTS_NAMESPACE.$DOMAIN_GKE135
    on_stop: stop_review_gke135
    auto_stop_in: 1 hour
  needs:
    - build_review_gke135

review_gke135:
  extends: .review_template
  variables:
    DOMAIN: $DOMAIN_GKE135
    AGENT_NAME: operator135-ci-cluster
    AGENT_PROJECT_PATH: gitlab-org/distribution/infrastructure/kube-agents
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context $AGENT_PROJECT_PATH:$AGENT_NAME
    - kubectl config set-context --current --namespace=$TESTS_NAMESPACE
  needs:
    - create_review_gke135
    # we need build_* dependency to receive appropriate artifacts
    - build_review_gke135
  environment: *environment_gke135
  resource_group: *env_gke_name135

qa_gke135:
  extends: .qa
  stage: qa
  variables:
    DOMAIN: $DOMAIN_GKE135
  needs:
    - review_gke135

qa_gke135_full_suite_trigger:
  extends: .qa_full_suite_trigger
  script: echo 'The job will trigger Full E2E suite against GKE 1.35'

qa_gke135_full:
  extends: .qa
  stage: qa
  parallel: 7
  variables:
    DOMAIN: $DOMAIN_GKE135
    QA_OPTIONS: $QA_FULL_SUITE_OPTIONS
  needs:
    - review_gke135
    - qa_gke135_full_suite_trigger

stop_review_gke135:
  extends: .stop_review_template
  variables:
    DOMAIN: $DOMAIN_GKE135
    AGENT_NAME: operator135-ci-cluster
    AGENT_PROJECT_PATH: gitlab-org/distribution/infrastructure/kube-agents
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context $AGENT_PROJECT_PATH:$AGENT_NAME
    - kubectl config set-context --current --namespace=$TESTS_NAMESPACE
  environment:
    name: *env_gke_name135
    action: stop
  needs:
    - build_review_gke135
