# frozen_string_literal: true

REVIEWERS_MESSAGE = <<~MSG
When requesting a review, it's recommended that you pick the reviewer suggested by the reviewer roulette, but you can pick someone else if you see fit.

Merge requests should receive a response within the limit documented in the [Review-response SLO](https://handbook.gitlab.com/handbook/engineering/workflow/code-review/#review-response-slo).

If you don't receive a response from the reviewer within the SLO, please mention `@gitlab-org\/software-delivery\/operate`, or one of our [Project Maintainers](https://handbook.gitlab.com/handbook/engineering/projects/#omnibus-gitlab)
MSG

# Print maintainers message
message(REVIEWERS_MESSAGE)
